### ISSUE TITLE
different slot_uris for 'subject_label' between oaklib & monarch-py schemas cause problems

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#319]
(monarch-ingest-N1lpQZPQ-py3.10) kschaper@kevin-ubuntu:~/monarch-ingest$ poetry run lsolr create-schema -C entity -s model.yaml -t Entity
Traceback (most recent call last):
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/bin/lsolr", line 8, in <module>
    sys.exit(main())
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/linkml_solr/cli.py", line 185, in create_schema
    schema_obj = YAMLGenerator(schema).schema
  File "<string>", line 24, in __init__
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/linkml/utils/generator.py", line 198, in __post_init__
    self._initialize_using_schemaloader(schema)
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/linkml/utils/generator.py", line 244, in _initialize_using_schemaloader
    loader.resolve()
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/linkml/utils/schemaloader.py", line 160, in resolve
    merge_schemas(
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/linkml/utils/mergeutils.py", line 53, in merge_schemas
    merge_dicts(target.slots, mergee.slots, imported_from, imported_from_uri, merge_imports)
  File "/home/kschaper/.cache/pypoetry/virtualenvs/monarch-ingest-N1lpQZPQ-py3.10/lib/python3.10/site-packages/linkml/utils/mergeutils.py", line 137, in merge_dicts
    raise ValueError(
ValueError: Conflicting URIs (https://w3id.org/oak/similarity, https://w3id.org/monarch/monarch-py) for item: subject_label

**Comment by putmantime** [comment]
Done
