### ISSUE TITLE
Association does not contain this entity error 

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#429]
Spotted in the logs:

monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    | 2023-10-23 16:54:57.469 | INFO     | monarch_py.api.middleware.logging_middleware:dispatch:26 - Request URL: http://monarchinitiative.org/v3/api/entity/MONDO:0017314 | Method: GET
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    | [2023-10-23 16:54:57 +0000] [11] [ERROR] Exception in ASGI application
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    | Traceback (most recent call last):
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 78, in call_next
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     message = await recv_stream.receive()
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/anyio/streams/memory.py", line 98, in receive
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     return self.receive_nowait()
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/anyio/streams/memory.py", line 91, in receive_nowait
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     raise EndOfStream
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    | anyio.EndOfStream
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    | During handling of the above exception, another exception occurred:
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    | Traceback (most recent call last):
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     result = await app(  # type: ignore[func-returns-value]
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     return await self.app(scope, receive, send)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     await super().__call__(scope, receive, send)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     await self.middleware_stack(scope, receive, send)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     raise exc
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     await self.app(scope, receive, _send)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 108, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     response = await self.dispatch_func(request, call_next)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/src/monarch_py/api/middleware/logging_middleware.py", line 39, in dispatch
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     response = await call_next(request)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 84, in call_next
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     raise app_exc
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 70, in coro
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     await self.app(scope, receive_or_disconnect, send_no_error)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     await self.app(scope, receive, send)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     raise exc
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     await self.app(scope, receive, sender)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     raise e
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     await self.app(scope, receive, send)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     await route.handle(scope, receive, send)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     await self.app(scope, receive, send)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     response = await func(request)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     raw_response = await run_endpoint_function(
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     return await dependant.call(**values)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/src/monarch_py/api/entity.py", line 28, in _get_entity
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     response = solr().get_entity(id, extra=True)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/src/monarch_py/implementations/solr/solr_implementation.py", line 89, in get_entity
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     node.inheritance = self._get_associated_entity(mode_of_inheritance_associations.items[0], node)
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |   File "/opt/monarch-app/backend/src/monarch_py/implementations/solr/solr_implementation.py", line 136, in _get_associated_entity
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    |     raise ValueError(f"Association does not contain this_entity: {this_entity.id}")
monarch-v3_api.1.gp2q4lfzaws8@monarch-v3-2023-10-17-api    | ValueError: Association does not contain this_entity: MONDO:0017314

**Comment by kevinschaper** [comment]
It looks like this is due to disease mode of inheritance bringing back an inheritance association to a parent term via the closure. I'm bringing in a PR to only get that association directly (don't look in the closure), but it's possible that the parent of a disease has a mode of inheritance, then the child terms should inherit that?

**Comment by kevinschaper** [comment]
http://monarchinitiative.org/v3/api/entity/MONDO:0017314 is now loading
