### ISSUE TITLE
entity api request fails for MONDO:0007038

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#54]
Running the API locally, and asking for http://localhost:8000/api/entity/MONDO:0007038 throws this exception. 

I think something about getting the neighborhood isn't None-safe? 

```
INFO:     127.0.0.1:49380 - "GET /api/entity/MONDO%3A0007038 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/kschaper/Documents/Monarch/monarch-api/backend/src/monarch_api/entity.py", line 47, in _get_entity
    node.inheritance = get_associated_entity(
TypeError: get_associated_entity() missing 1 required positional argument: 'this_entity'

```

**Comment by glass-ships** [comment]
For reference, using the python CLI doesn't complain about this:
```bash
$ monarch entity MONDO:0007038

{
    "id": "MONDO:0007038",
    "category": [
        "biolink:Disease"
    ],
    "name": "Achoo syndrome",
    "description": null,
    "xref": [],
    "provided_by": "phenio_nodes",
    "in_taxon": null,
    "source": null,
    "symbol": null,
    "type": null,
    "synonym": []
}
```

**Comment by glass-ships** [comment]
this seems to be working as of monarch-py v0.7.2 + latest solr at time of writing

Re-open if it starts causing trouble again!
