### ISSUE TITLE
Fix monarch-app schema causing schemaloader error in linkml-solr at linkml 1.7

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#716]
The 2024-05 build has been silently failing to use the schema for Solr, meaning that the ingest finishes, but the resulting solr.tar.gz has every field multivalued. 

I added `set -e` to the load_solr.sh bash script, so that it actually halts on errors. I need to also handle the error in the ingest python cli wrapper to make sure that the build actually halts on this problem. 

This is the actual schemaloader error that we need to solve:

```
Traceback (most recent call last):
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/bin/lsolr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/linkml_solr/cli.py", line 192, in create_schema
    gen = qe.load_schema(dry_run=dry_run)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/linkml_solr/query.py", line 279, in load_schema
    gen = SolrSchemaGenerator(self.schema, top_class=self.top_class)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/linkml_solr/solrschemagen.py", line 50, in __init__
    super().__init__(schema, **kwargs)
  File "<string>", line 24, in __init__
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/linkml/utils/generator.py", line 204, in __post_init__
    self._initialize_using_schemaloader(schema)
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/linkml/utils/generator.py", line 251, in _initialize_using_schemaloader
    loader.resolve()
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/linkml/utils/schemaloader.py", line 145, in resolve
    merge_schemas(
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/linkml/utils/mergeutils.py", line 54, in merge_schemas
    merge_dicts(target.types, mergee.types, imported_from, imported_from_uri, merge_imports)
  File "/Users/kschaper/Monarch/monarch-ingest/.venv/lib/python3.11/site-packages/linkml/utils/mergeutils.py", line 134, in merge_dicts
    raise ValueError(f"Conflicting URIs ({source[k].from_schema}, {target[k].from_schema}) for item: {k}")
ValueError: Conflicting URIs (https://w3id.org/linkml/types, https://w3id.org/monarch/monarch-py) for item: string
```

**Comment by kevinschaper** [comment]
This is resolved with fixes to linkml-solr
